apiVersion: apps/v1
kind: Deployment
metadata:
  name: djando-app-deployment
  labels:
    app: django-app
  namespace: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      serviceAccountName: task-service-account
      containers:
        - name: djando-app
          image: mokhtar74/simple-ci-cd:redis-postgres-V3
          ports:
            - containerPort: 8000
          env:
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  name: hippo-pguser-hippo
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: hippo-pguser-hippo
                  key: port
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: hippo-pguser-hippo
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hippo-pguser-hippo
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hippo-pguser-hippo
                  key: password