apiVersion: apps/v1
kind: Deployment
metadata:
  name: djando-app-deployment
  labels:
    app: django-app
  namespace: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: djando-app
          image: mokhtar74/simple-ci-cd:redis-postgres-1
          ports:
            - containerPort: 8000
          env:
          - name: DB_ADDR
            valueFrom:
              secretKeyRef:
                name: hippo-pguser-hippo
                key: host
                namespace: postgres-operator
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: hippo-pguser-hippo
                key: port
                namespace: postgres-operator
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: hippo-pguser-hippo
                key: dbname
                namespace: postgres-operator
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: hippo-pguser-hippo
                key: user
                namespace: postgres-operator
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hippo-pguser-hippo
                key: password
                namespace: postgres-operator