apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: task-service-account
  namespace: task
roleRef:
  kind: ClusterRole
  name: secret-reader-cluster-role
  apiGroup: rbac.authorization.k8s.io
